require 'hipbot-plugins/human'
require 'hipbot-plugins/ascii'
# require 'hipbot-plugins/dictionary'
require 'hipbot-plugins/excuses'
require 'hipbot-plugins/github'
require 'hipbot-plugins/google'
require 'hipbot-plugins/help'
require 'hipbot-plugins/human'
# require 'hipbot-plugins/meme_generator'
# require 'hipbot-plugins/numbers_api'
require 'hipbot-plugins/rapportive'
require 'hipbot-plugins/wolfram_alpha'

require 'babot/plugins/alive'
require 'babot/plugins/giphy'
require 'babot/plugins/quotes'
require 'babot/plugins/meme_generator'
require 'babot/plugins/chuck'
require 'babot/plugins/github'
require 'babot/plugins/insult'
require 'babot/plugins/numbers'
require 'babot/plugins/yo_mama'
require 'babot/plugins/babbel_excuse'
require 'babot/plugins/clfln'
